"""create tables: categories, product, product_variants, modifier_group_associations, modifier_groups, modifiers and combo_bundles

Revision ID: ce6454f9ff7d
Revises: 5423c52de4f4
Create Date: 2025-06-15 15:29:17.514744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce6454f9ff7d"
down_revision: Union[str, None] = "5423c52de4f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_index(
        op.f("ix_categories_sort_order"),
        "categories",
        ["sort_order"],
        unique=False,
    )
    op.create_table(
        "modifier_groups",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("is_multiselect", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifier_groups")),
    )
    op.create_table(
        "modifiers",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("price_delta", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["modifier_groups.id"],
            name=op.f("fk_modifiers_group_id_modifier_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modifiers")),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("name", name=op.f("uq_products_name")),
    )
    op.create_index(
        op.f("ix_products_sort_order"),
        "products",
        ["sort_order"],
        unique=False,
    )
    op.create_table(
        "product_variants",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=True),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_combo", sa.Boolean(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
    )
    op.create_index(
        op.f("ix_product_variants_sku"),
        "product_variants",
        ["sku"],
        unique=True,
    )
    op.create_table(
        "combo_bundles",
        sa.Column("combo_variant_id", sa.Integer(), nullable=False),
        sa.Column("included_variant_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["combo_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_combo_bundles_combo_variant_id_product_variants"),
        ),
        sa.ForeignKeyConstraint(
            ["included_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_combo_bundles_included_variant_id_product_variants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_combo_bundles")),
        sa.UniqueConstraint(
            "combo_variant_id",
            "included_variant_id",
            name="idx_unique_combo_variant_included_variant",
        ),
    )
    op.create_table(
        "modifier_group_associations",
        sa.Column("product_variant_id", sa.Integer(), nullable=False),
        sa.Column("modifier_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["modifier_group_id"],
            ["modifier_groups.id"],
            name=op.f(
                "fk_modifier_group_associations_modifier_group_id_modifier_groups"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
            name=op.f(
                "fk_modifier_group_associations_product_variant_id_product_variants"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "product_variant_id",
            "modifier_group_id",
            name=op.f("pk_modifier_group_associations"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("modifier_group_associations")
    op.drop_table("combo_bundles")
    op.drop_index(
        op.f("ix_product_variants_sku"), table_name="product_variants"
    )
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_products_sort_order"), table_name="products")
    op.drop_table("products")
    op.drop_table("modifiers")
    op.drop_table("modifier_groups")
    op.drop_index(op.f("ix_categories_sort_order"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
