"""add soft delete mixin

Revision ID: 8e136f43f957
Revises: ce6454f9ff7d
Create Date: 2025-06-16 14:03:59.969264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e136f43f957"
down_revision: Union[str, None] = "ce6454f9ff7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_categories_is_deleted"),
        "categories",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "modifier_groups",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_modifier_groups_is_deleted"),
        "modifier_groups",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "modifiers",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_modifiers_is_deleted"),
        "modifiers",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "product_variants",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_product_variants_is_deleted"),
        "product_variants",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "products",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_products_is_deleted"),
        "products",
        ["is_deleted"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_is_deleted"), table_name="products")
    op.drop_column("products", "is_deleted")
    op.drop_index(
        op.f("ix_product_variants_is_deleted"), table_name="product_variants"
    )
    op.drop_column("product_variants", "is_deleted")
    op.drop_index(op.f("ix_modifiers_is_deleted"), table_name="modifiers")
    op.drop_column("modifiers", "is_deleted")
    op.drop_index(
        op.f("ix_modifier_groups_is_deleted"), table_name="modifier_groups"
    )
    op.drop_column("modifier_groups", "is_deleted")
    op.drop_index(op.f("ix_categories_is_deleted"), table_name="categories")
    op.drop_column("categories", "is_deleted")
    # ### end Alembic commands ###
